In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split

In [253]:
tabla = pd.read_csv("200503COVID19MEXICO.csv")

In [254]:
print(tabla.describe)

<bound method NDFrame.describe of       FECHA_ACTUALIZACION ID_REGISTRO  ORIGEN  SECTOR  ENTIDAD_UM  SEXO  \
0              2020-05-03      134d54       1       4          17     2   
1              2020-05-03      05f125       1       4           9     1   
2              2020-05-03      0d2268       1       4           2     2   
3              2020-05-03       63132       1       4           9     2   
4              2020-05-03      0c0bda       1      12          14     1   
...                   ...         ...     ...     ...         ...   ...   
95834          2020-05-03      155675       1       4          23     2   
95835          2020-05-03      10233e       1       4           2     2   
95836          2020-05-03      11f506       1      12          27     1   
95837          2020-05-03      139147       2      12          15     1   
95838          2020-05-03      1a681e       2      12           9     2   

       ENTIDAD_NAC  ENTIDAD_RES  MUNICIPIO_RES  TIPO_PACIENTE  ..

In [256]:
del tabla['FECHA_ACTUALIZACION']
del tabla['ID_REGISTRO']
del tabla['MIGRANTE']
del tabla['PAIS_NACIONALIDAD']
del tabla['PAIS_ORIGEN']

In [257]:
tabla

ORIGEN  SECTOR  ENTIDAD_UM  SEXO  ENTIDAD_NAC  ENTIDAD_RES  \
0           1       4          17     2           17           17   
1           1       4           9     1            9            9   
2           1       4           2     2           25            2   
3           1       4           9     2            9            9   
4           1      12          14     1           14           14   
...       ...     ...         ...   ...          ...          ...   
95834       1       4          23     2            7           23   
95835       1       4           2     2            2            2   
95836       1      12          27     1            4           27   
95837       2      12          15     1            9           15   
95838       2      12           9     2            9            9   

       MUNICIPIO_RES  TIPO_PACIENTE FECHA_INGRESO FECHA_SINTOMAS  ...  \
0                  6              1    2020-03-09     2020-03-09  ...   
1                 15              1    2020-03-19     2020-03-17  ...   
2                  2              2    2020-03-19     2020-03-19  ...   
3                 15              2    2020-03-30     2020-03-24  ...   
4                 39              2    2020-03-29     2020-03-26  ...   
...              ...            ...           ...            ...  ...   
95834              5              2    2020-05-01     2020-04-30  ...   
95835              2              2    2020-04-27     2020-04-27  ...   
95836              4              2    2020-05-03     2020-04-28  ...   
95837             58              1    2020-05-03     2020-05-01  ...   
95838              7              1    2020-05-03     2020-05-02  ...   

      INMUSUPR  HIPERTENSION  OTRA_COM  CARDIOVASCULAR  OBESIDAD  \
0            2             2         2               2         2   
1            2             2         2               2         2   
2            2             1         2               2         1   
3            2             2         2               2         2   
4            2             2         2               2         2   
...        ...           ...       ...             ...       ...   
95834        2             2         2               2         2   
95835        1             1         2               2         2   
95836        2             1         2               2         2   
95837        2             2         2               2         2   
95838        2             2         2               2         2   

       RENAL_CRONICA  TABAQUISMO  OTRO_CASO  RESULTADO  UCI  
0                  2           2         99          1   97  
1                  2           2         99          1   97  
2                  2           2         99          1    2  
3                  2           2         99          1    2  
4                  2           2          2          2    2  
...              ...         ...        ...        ...  ...  
95834              2           2         99          3    2  
95835              1           2         99          3    2  
95836              2           2         99          3    2  
95837              2           2          1          3   97  
95838              2           2          1          3   97  

[95839 rows x 30 columns]

In [258]:
#separamos la Y que sera si el paciente murio o no
x=tabla
y=tabla['FECHA_DEF']
del x ['FECHA_DEF']

xx=x.values
yy=y.values


In [259]:
#transformamo la fecha de defuncion a binario
for i in range(yy.size):
    if yy[i]=="9999-99-99":
        yy[i]=0
    else:
        yy[i]=1
      


In [260]:
#transformamos la fecha de ingreso y sintomas a un numero entero
for i in range(yy.size):
    xx[i][8]=((int)(xx[i][8].split('-')[0])*1000)+((int)(xx[i][8].split('-')[1])*100)+((int)(xx[i][8].split('-')[2]))
    xx[i][9]=((int)(xx[i][9].split('-')[0])*1000)+((int)(xx[i][9].split('-')[1])*100)+((int)(xx[i][9].split('-')[2]))

    

In [ ]:
#particionado de los datos

In [261]:
xtrain,xtest,ytrain,ytest=train_test_split(xx,yy)

In [262]:
ytrain=ytrain.astype('int')
ytest=ytest.astype('int')

# kmedias   Nota : nos salio un score raro para este algoritmo :(

Definimos cuantos centroide seran

In [276]:
kmedias= KMeans(n_clusters=2)

entrenamos

In [277]:
kmedias.fit(xtrain)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=2, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [278]:
kmedias.cluster_centers_

array([[1.68189650e+00, 8.68266888e+00, 1.49560929e+01, 1.46901551e+00,
        1.81467530e+01, 1.51259581e+01, 3.88942428e+01, 1.24276632e+00,
        2.02032907e+06, 2.02030757e+06, 7.39269206e+01, 1.84902858e+00,
        3.93359278e+01, 1.03190541e+00, 4.66654388e+01, 2.30740895e+00,
        1.99691046e+00, 2.06464262e+00, 2.04711544e+00, 2.10611372e+00,
        1.94189294e+00, 2.05252213e+00, 2.07046521e+00, 1.93725863e+00,
        2.08817064e+00, 1.99114729e+00, 4.34813737e+01, 1.84314657e+00,
        7.39240093e+01],
       [1.59753306e+00, 9.60338250e+00, 1.45925193e+01, 1.52139951e+00,
        1.58698590e+01, 1.48443722e+01, 3.43790328e+01, 1.27577750e+00,
        2.02042512e+06, 2.02041783e+06, 7.08081493e+01, 1.81454367e+00,
        4.28858451e+01, 1.00659425e+00, 5.18018093e+01, 4.41818050e+00,
        2.34313690e+00, 2.45407644e+00, 2.43914402e+00, 2.48018093e+00,
        2.29061910e+00, 2.62367388e+00, 2.46968101e+00, 2.29557840e+00,
        2.45736448e+00, 2.38479145e+00,

In [279]:
kmedias.labels_

array([1, 1, 1, ..., 1, 0, 1], dtype=int32)

comprobamos la prediccion 

In [280]:
kmedias.predict(xtest)

array([1, 1, 1, ..., 0, 1, 1], dtype=int32)

In [281]:
ytest

array([0, 0, 0, ..., 1, 0, 0])

In [282]:
kmedias.score(xtrain,ytrain)

-954739034.9580078

# knn

In [270]:
from sklearn.neighbors import KNeighborsClassifier

In [295]:
knn=KNeighborsClassifier(n_neighbors=3)

In [296]:
knn.fit(xtrain,ytrain)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [297]:
knn.predict(xtest)

array([0, 0, 0, ..., 0, 0, 0])

In [298]:
knn.score(xtest,ytest)

0.9565525876460768

# regresion logistica

In [300]:
from sklearn.linear_model import LogisticRegression

Creamos el objeto y entrenamos

In [301]:
regresion_logistica=LogisticRegression()
regresion_logistica=regresion_logistica.fit(xtrain,ytrain)

/home/diego/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Comprobemos la eficiencia del algoritmo 

In [302]:
regresion_logistica.predict(xtest)

array([0, 0, 0, ..., 0, 0, 0])

In [303]:
regresion_logistica.score(xtest,ytest)

0.9632303839732889